version: '3.8'

services:

  rest-app:
    container_name: "rest-app"
    build:
      context: ./
      dockerfile: ./docker/DockerApp
      args:
        WORKDIR: ${WORKING_DIR}
    networks:
      - local
    depends_on:
      - rest-db
    volumes:
      - ./app:${WORKING_DIR}
    env_file:
      - ".env"
    expose:
      - "8080"
    ports:
      - "8080:8080"

  rest-db:
    container_name: "rest-db"
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql

  db-migrations:
    container_name: "migrate"
    build:
      dockerfile: ./docker/DockerMigrate
      context: .
      args:
        WORKDIR: ${WORKING_DIR}
    env_file:
      - ".env"
    volumes:
      - ./migrations:${WORKING_DIR}/migrations
      - ./shell:${WORKING_DIR}/shell
    tty: true

volumes:
  mysql-volume:
networks:
  local: